// ===== DO NOT EDIT, CHANGES WILL BE OVERWRITTEN =====
// automatically generated by get_contributor_user_info.py

package org.akanework.gramophone.logic.utils.data

import android.net.Uri
import org.akanework.gramophone.R

object Contributors {
    private fun decode(text: String?) = text?.let { Uri.decode(it) }
    val LIST = listOf(
        GitHubUser(login = "nift4", name = decode("Nick"), avatar = R.drawable.contributor_nift4, contributed = R.string.contributors_nift4),
        GitHubUser(login = "123Duo3", name = decode("123Duo3"), avatar = R.drawable.contributor_123duo3, contributed = R.string.contributors_123duo3),
        GitHubUser(login = "AkaneTan", name = decode("%E3%81%82%E3%81%8B%E3%81%AD"), avatar = R.drawable.contributor_akanetan, contributed = R.string.contributors_akanetan),
        GitHubUser(login = "imjyotiraditya", name = decode("Jyotiraditya%20Panda"), avatar = R.drawable.contributor_imjyotiraditya, contributed = R.string.contributors_developer),
        GitHubUser(login = "WSTxda", name = decode("WSTxda"), avatar = R.drawable.contributor_wstxda, contributed = R.string.contributors_wstxda),
        GitHubUser(login = "pxeemo", name = decode("Shayan"), avatar = R.drawable.contributor_pxeemo, contributed = R.string.contributors_pxeemo),
        GitHubUser(login = "Lambada10", name = decode(null), avatar = R.drawable.contributor_lambada10, contributed = R.string.contributors_lambada10),
        GitHubUser(login = "lightsummer233", name = decode("Light_summer"), avatar = R.drawable.contributor_lightsummer233, contributed = R.string.contributors_developer),
        GitHubUser(login = "nicholaswww", name = decode("Nicholas"), avatar = R.drawable.contributor_nicholaswww, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "Yuyuko1024", name = decode("JunkoYuko"), avatar = R.drawable.contributor_yuyuko1024, contributed = R.string.contributors_yuyuko1024),
        GitHubUser(login = "ghhccghk", name = decode("%E6%9D%8E%E5%A4%AA%E7%99%BD"), avatar = R.drawable.contributor_ghhccghk, contributed = R.string.contributors_ghhccghk),
        GitHubUser(login = "lucaxvi", name = decode(null), avatar = R.drawable.contributor_lucaxvi, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "tungnk123", name = decode(null), avatar = R.drawable.contributor_tungnk123, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "topazrn", name = decode("Topaz%20RN"), avatar = R.drawable.contributor_topazrn, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "strongville", name = decode("Guillermo%20Villafuerte"), avatar = R.drawable.contributor_strongville, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "bggRGjQaUbCoE", name = decode("dom"), avatar = R.drawable.contributor_bggrgjqaubcoe, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "VishnuSanal", name = decode("Vishnu%20Sanal%20T"), avatar = R.drawable.contributor_vishnusanal, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "mikooomich", name = decode("Michael%20Zh"), avatar = R.drawable.contributor_mikooomich, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "HotarunIchijou", name = decode("Kaorun"), avatar = R.drawable.contributor_hotarunichijou, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "someone5678", name = decode("someone5678"), avatar = R.drawable.contributor_someone5678, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "IzzySoft", name = decode("Izzy"), avatar = R.drawable.contributor_izzysoft, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "PalanixYT", name = decode("Palanix"), avatar = R.drawable.contributor_palanixyt, contributed = R.string.contributors_code_contributions),
        GitHubUser(login = "N3Shemmy3", name = decode("Shemmy"), avatar = R.drawable.contributor_n3shemmy3, contributed = R.string.contributors_code_contributions),
    )
}
